version: '3.8'

services:
  backend:
    build: ./fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  frontend:
    build: ./next-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./next-frontend:/app
      - /app/node_modules  # Preserve node_modules inside the container
    depends_on:
      - backend
    restart: always